using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.IO;

namespace WindowsFormsApplication2
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            using (StreamWriter writer = new StreamWriter(@"C:\" + textBox2.Text+ "_syllabus.html"))
            {
                writer.WriteLine("<link rel='preload' href='https://www.ieu.edu.tr/css/yenicss/1.min.css?ver=1.2' media='screen' as='style'>");
                writer.WriteLine("<link href='https://www.ieu.edu.tr/css/yenicss/1.min.css?ver=1.2' rel='stylesheet'>");
                writer.WriteLine("<div>");
                writer.WriteLine("<div class='card'>");
                writer.WriteLine("<div class='card-body'>");
                writer.WriteLine("<div class='table-responsive'>");
                writer.WriteLine("<table align='center' cellpadding='2' cellspacing='2' class='table table-condensed table-bordered '>");
                writer.WriteLine("<tbody>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td class='sy-label' style='padding:20px;'>");
                writer.WriteLine("<strong>" + "Dersin Adı");
                writer.WriteLine("</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td style='padding:20px;'>");
                writer.WriteLine("<div class='editinput' id='course_name'>" + textBox1.Text);
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>");
                writer.WriteLine("</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("<div class='table-responsive'>");
                writer.WriteLine("<table align='center' cellpadding='2' cellspacing='2' class='table table-condensed table-bordered transpose'>");
                writer.WriteLine("<tbody>");
                writer.WriteLine("<tr class='sy-label'>");
                writer.WriteLine("<td scope='col'>");
                writer.WriteLine("<div align='center'>");
                writer.WriteLine("<strong>" + "Kodu");
                writer.WriteLine("</strong>");
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td scope='col'>");
                writer.WriteLine("<div align='center'>");
                writer.WriteLine("<strong>" + "Yarıyıl");
                writer.WriteLine("</strong>");
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td scope='col'>");
                writer.WriteLine("<div align='center'>");
                writer.WriteLine("<strong>" + "Teori");
                writer.WriteLine("<br>" + "(saat/hafta)");
                writer.WriteLine("</strong>");
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td scope='col'>");
                writer.WriteLine("<div align='center'>");
                writer.WriteLine("<strong>" + "Uygulama/Lab");
                writer.WriteLine("<br>" + "(saat/hafta)");
                writer.WriteLine("</strong>");
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td scope='col'>");
                writer.WriteLine("<div align='center'>");
                writer.WriteLine("<strong>" + "Yerel Kredi");
                writer.WriteLine("</strong>");
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td scope='col'>");
                writer.WriteLine("<div align='center'>");
                writer.WriteLine("<strong>" + "AKTS");
                writer.WriteLine("</strong>");
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div align='center'>" + textBox2.Text);
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='semester' class='editinput' align='center'>" + textBox3.Text);
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div align='center' id='weekly_hours' class='editinput'>" + textBox4.Text);
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div align='center' id='app_hours' class='editinput'>" + textBox5.Text);
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='ieu_credit' class='editinput' align='center'>" + textBox6.Text);
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='ects_credit' class='editinput' align='center'>" + textBox7.Text);
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>");
                writer.WriteLine("</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("<br>");
                writer.WriteLine("<div class='table-responsive'>");
                writer.WriteLine("<table align='center' cellpadding='2' cellspacing='2' class='table table-condensed table-bordered'>");
                writer.WriteLine("<tbody>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td style='width:20%' valign='top' class='sy-label'>");
                writer.WriteLine("<strong>" + "Ön Koşul(lar)");
                writer.WriteLine("</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td colspan='6'>");
                writer.WriteLine("<div id='pre_requisites'>");
                writer.WriteLine("<table width='100%'>");
                writer.WriteLine("<tbody>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td style='border:none;'>" + "&nbsp;" + "</td>");
                writer.WriteLine("<td style='border:none;'>" + textBox8.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>");
                writer.WriteLine("</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td class='sy-label'>");
                writer.WriteLine("<strong>" + "Dersin Dili");
                writer.WriteLine("</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div class='editinput' id='course_lang'>" + textBox9.Text);
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td class='sy-label'>");
                writer.WriteLine("<strong>" + "Dersin Türü");
                writer.WriteLine("</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div class='editinput' id='course_type'>" + textBox10.Text);
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td class='sy-label'>");
                writer.WriteLine("<strong>" + "Dersin Düzeyi");
                writer.WriteLine("</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div class='editselect' id='course_level'>" + textBox11.Text);
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td class='sy-label'>");
                writer.WriteLine("<strong>" + "Dersin Koordinatörü");
                writer.WriteLine("</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<ul id='coordinator_list'>" + "<li>" + textBox12.Text + "</li>" + "</ul>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td valign='top' class='sy-label'>");
                writer.WriteLine("<strong>" + "Öğretim Elemanı");
                writer.WriteLine("</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<ul id='lecturer_list'>");
                writer.WriteLine("<li>" + textBox13.Text + "</li>");
                writer.WriteLine("</ul>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td class='sy-label'>");
                writer.WriteLine("<strong>" + "Yardımcıları");
                writer.WriteLine("</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<ul id='lecturer_list'>");
                writer.WriteLine("<li>" + textBox14.Text + "</li>");
                writer.WriteLine("</ul>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>");
                writer.WriteLine("</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("<div class='table-responsive'>");
                writer.WriteLine("<table align='center' cellpadding='2' cellspacing='2' class='table table-condensed table-bordered'>");
                writer.WriteLine("<tbody>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td style='width:20%' valign='top' class='sy-label'>");
                writer.WriteLine("<strong>" + "Dersin Amacı");
                writer.WriteLine("</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox15.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td valign='top' class='sy-label'>");
                writer.WriteLine("<strong>" + "Öğrenme Çıktıları");
                writer.WriteLine("</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<span>" + "Bu dersi başarıyla tamamlayan öğrenciler;");
                writer.WriteLine("</span>");
                writer.WriteLine("<ul id='outcome'>");
                writer.WriteLine("<li id='li0'>" + textBox16.Text + "</li>");
                writer.WriteLine("</ul>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td valign='top' class='sy-label'>");
                writer.WriteLine("<strong>" + "Ders Tanımı");
                writer.WriteLine("</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox17.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>");
                writer.WriteLine("</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("<p>" + "&nbsp;" + "</p>");
                writer.WriteLine("<div class='table-responsive'>");
                writer.WriteLine("<table align='center' cellpadding='2' cellspacing='2' class='table table-condensed table-bordered'>");
                writer.WriteLine("<tbody>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td rowspan='5' class='sy-label' style='width:20%'");
                writer.WriteLine("<div align='center'>");
                writer.WriteLine("<p><br><br>");
                writer.WriteLine("<strong>" + "Dersin Kategorisi" + "</strong>");
                writer.WriteLine("</p>");
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + "Temel Ders" + "</td>");
                writer.WriteLine("<td class='veri'>");
                writer.WriteLine("<div id='core_course' class='editcat' align='center'>" + textBox18.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Uzmanlık/Alan Dersleri" + "</td>");
                writer.WriteLine("<td class='veri' width='50'>");
                writer.WriteLine("<div id='major_area' class='editcat' align='center'>" + textBox19.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Destek Dersleri" + "</td>");
                writer.WriteLine("<td class='veri' width='50'>");
                writer.WriteLine("<div align='center' class='editcat' id='supportive_courses'>" + textBox20.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "İletişim ve Yönetim Becerileri Dersleri" + "</td>");
                writer.WriteLine("<td class='veri' width='50'>");
                writer.WriteLine("<div id='media_man_skills' class='editcat' align='center'>" + textBox21.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Aktarılabilir Beceri Dersleri" + "</td>");
                writer.WriteLine("<td class='veri' width='50'>");
                writer.WriteLine("<div id='trans_skills' class='editcat' align='center'>" + textBox22.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>" + "</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("<p>" + "&nbsp;" + "</p>");
                writer.WriteLine("<div>" + "<h3>");
                writer.WriteLine("<strong>" + "HAFTALIK KONULAR VE İLGİLİ ÖN HAZIRLIK ÇALIŞMALARI" + "</strong>");
                writer.WriteLine("</h3>" + "</div>");
                writer.WriteLine("<div class='table-responsive'>");
                writer.WriteLine("<table align='center' cellpadding='2' cellspacing='2' class='table table-condensed table-bordered' id='weeks'>");
                writer.WriteLine("<tbody>" + "<tr class='table_top'>");
                writer.WriteLine("<td class='text-center' style='width:5%'>");
                writer.WriteLine("<strong>" + "Hafta" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "Konular" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td style:'width:30%'>");
                writer.WriteLine("<strong>" + "Ön Hazırlık" + "</strong>");
                writer.WriteLine("</td>" + "</tr>");
                writer.WriteLine("<tr id='hafta_1'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "1" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox23.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox24.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_2'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "2" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox25.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox26.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_3'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "3" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox27.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox28.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_4'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "4" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox29.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox30.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_5'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "5" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox31.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox32.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_6'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "6" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox33.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox34.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_7'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "7" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox35.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox36.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_8'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "8" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox37.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox38.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_9'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "9" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox39.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox40.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_10'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "10" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox41.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox42.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_11'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "11" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox43.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox44.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_12'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "12" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox45.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox46.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_13'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "13" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox47.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox48.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_14'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "14" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox49.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox50.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_15'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "15" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox51.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox52.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_16'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "16" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox53.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox54.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>" + "</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("<br>");
                writer.WriteLine("<div class='table-responsive'>");
                writer.WriteLine("<table align='center' cellpadding='2' cellspacing='2' class='table table-condensed table-bordered'>");
                writer.WriteLine("<tbody>" + "<tr>");
                writer.WriteLine("<td style='width:20%' valign='top'>");
                writer.WriteLine("<strong>" + "Ders Kitabı" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + "<p>" + textBox55.Text + "</p>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td valign='top'>");
                writer.WriteLine("<strong>" + "Önerilen Okumalar/Materyaller" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + "<p>" + textBox56.Text + "</p>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>" + "</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("<p>" + "&nbsp;" + "</p>");
                writer.WriteLine("<div>");
                writer.WriteLine("<h3>" + "<strong>" + "DEĞERLENDİRME ÖLÇÜTLERİ" + "</strong>" + "</h3>");
                writer.WriteLine("</div>");
                writer.WriteLine("<div class='table-responsive'>");
                writer.WriteLine("<table align='center' cellpadding='2' cellspacing='2' class='table table-condensed table-bordered' id='evaluation_table1'>");
                writer.WriteLine("<tbody>" + "<tr class='table-top'>");
                writer.WriteLine("<td style:'width:70%'>" + "<strong>" + "Yarıyıl Aktiviteleri" + "</strong>" + "</td>");
                writer.WriteLine("<td style:'width:15%' align='center'>" + "<strong>" + "Sayı" + "</strong>" + "</td>");
                writer.WriteLine("<td style:'width:15%' align='center'>" + "<strong>" + "Katkı Payı %" + "</strong>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Katılım" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='attendance_no'>" + textBox57.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='attendance_per'>" + textBox58.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Labaratuvar/Uygulama" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='lab_no'>" + textBox59.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='lab_per'>" + textBox60.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Arazi Çalışması" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='fieldwork_no'>" + textBox61.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='fieldwork_per'>" + textBox62.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Küçük Sınav/ Stüdyo Kritiği" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='quiz_no'>" + textBox63.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='quiz_per'>" + textBox64.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Ödev" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='homework_no'>" + textBox65.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='homework_per'>" + textBox66.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Sunum / Jüri Önünde Sunum" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='presentation_no'>" + textBox67.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='presentation_per'>" + textBox68.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Proje" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='project_no'>" + textBox69.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='project_per'>" + textBox70.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Seminer / Çalıştay" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='seminar_no'>" + textBox71.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='seminar_per'>" + textBox72.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Sözlü Sınav" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='portfolios__no'>" + textBox73.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='portfolios_per'>" + textBox74.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Ara Sınav" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='midterm_no'>" + textBox75.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='midterm_per'>" + textBox76.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Final Sınavı" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='final_no'>" + textBox77.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='final_per'>" + textBox78.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td align='right'>");
                writer.WriteLine("<strong>" + "Toplam" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div class='editinput' id='ara_total_no'>" + textBox79.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div class='editinput' id='ara_total_per'>" + textBox80.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>" + "</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("<br>");
                writer.WriteLine("<div class='table-responsive'>");
                writer.WriteLine("<table align='center' cellpadding='2' cellspacing='2' class='table table-condensed table-bordered' id='evaluation_table2'>");
                writer.WriteLine("<tbody>" + "<tr style='background-color:#ff6600; color:#fff; font-weight:100;'>");
                writer.WriteLine("<td style='width:70%'>" + "Yarıyıl Çalışmalarının Başarı Notuna Katkısı" + "</td>");
                writer.WriteLine("<td style='width:15%' align='center' width='150'>" + "<div>" + textBox81.Text + "</div>" + "</td>");
                writer.WriteLine("<td style='width:15%' align='center' width='150'>" + "<div>" + textBox82.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr style='background-color:#df520f; color:#fff; font-weight:400;'>");
                writer.WriteLine("<td>" + "Yarıyıl sonu Çalışmalarının Başarı Notuna Katkısı" + "</td>");
                writer.WriteLine("<td align='center' width='150'>" + "<div>" + textBox83.Text + "</div>" + "</td>");
                writer.WriteLine("<td align='center' width='150'>" + "<div>" + textBox84.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td align='right'>" + "<strong>" + "Toplam" + "</strong>" + "</td>");
                writer.WriteLine("<td align='center' id='total_no' style='font-weight: bold;'>" + textBox85.Text + "</td>");
                writer.WriteLine("<td align='center' id='total_no' style='font-weight: bold;'>" + textBox86.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>" + "</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("<div>");
                writer.WriteLine("<h3>" + "<strong>" + "AKTS/ İŞ YÜKÜ TABLOSU" + "</strong>" + "</h3>");
                writer.WriteLine("</div>");
                writer.WriteLine("<div class='table-responsive'>");
                writer.WriteLine("<table align='center' cellpadding='2' cellspacing='2' class='table table-condensed table-bordered' id='workload_table'>");
                writer.WriteLine("<thead>");
                writer.WriteLine("<tr class='table_top'>");
                writer.WriteLine("<th style='width:55%'>" + "<strong>" + "Yarıyıl Aktiviteleri" + "</strong>" + "</th>");
                writer.WriteLine("<th style='width:15%' class='text-center'>" + "<strong>" + "Sayı" + "</strong>" + "</th>");
                writer.WriteLine("<th style='width:15%' class='text-center'>" + "<strong>" + "Süre (Saat)" + "</strong>" + "</th>");
                writer.WriteLine("<th style='width:15%' class='text-center'>" + "<strong>" + "İş Yükü" + "</strong>" + "</th>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</thead>");
                writer.WriteLine("<tbody>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Teorik Ders Saati" + "<br>" + "<small>" + "<i>" + "(Sınav Haftası Dahildir: 16 x Teorik Ders Saati)" + "</i>" + "</small>" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='course_hour_number' class='editinput'>" + textBox87.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='course_hour_duration' class='editinput'>" + textBox88.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='course_hour_total_workload' class='editinput'>" + textBox89.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Labaratuvar/Uygulama Ders Saati" + "<br>" + "<small>" + "<i>" + "(Sınav Haftası Dahildir: 16 x Labaratuvar/Uygulama Ders Saati)" + "</i>" + "</small>" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='lab_number' class='editinput'>" + textBox90.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='lab_duration' class='editinput'>" + textBox91.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='lab_total_workload' class='editinput'>" + textBox92.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Sınıf Dışı Ders Çalışması" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='out_hour_number' class='editinput'>" + textBox93.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='out_hour_duration' class='editinput'>" + textBox94.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='out_hour_duration_total_workload' class='editinput'>" + textBox95.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Arazi Çalışması" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='fieldwork_number' class='editinput'>" + textBox96.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='fieldwork_duration' class='editinput'>" + textBox97.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='fielwork_total_number' class='editinput'>" + textBox98.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Küçük Sınav / Stüdyo Kritiği" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='quizess_number' class='editinput'>" + textBox99.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='quizess_duration' class='editinput'>" + textBox100.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='quizess_total_workload' class='editinput'>" + textBox101.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Ödev" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='homework_number' class='editinput'>" + textBox102.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='homework_duration' class='editinput'>" + textBox103.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='homework_total_workload' class='editinput'>" + textBox104.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Sunum / Jüri Önünde Sunum" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='presentation_number' class='editinput'>" + textBox105.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='presentation_duration' class='editinput'>" + textBox106.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='presentation_total_workload' class='editinput'>" + textBox107.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Proje" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='project_number' class='editinput'>" + textBox108.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='project_duration' class='editinput'>" + textBox109.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='project_total_workload' class='editinput'>" + textBox110.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Seminer / Çalıştay" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='seminar_number' class='editinput'>" + textBox111.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='seminar_duration' class='editinput'>" + textBox112.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='seminar_total_workload' class='editinput'>" + textBox113.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Sözlü Sınav" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='portfolios_number' class='editinput'>" + textBox114.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='portfolios_duration' class='editinput'>" + textBox115.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='portfolios_total_workload' class='editinput'>" + textBox116.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Ara Sınavlar" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='midterm_number' class='editinput'>" + textBox117.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='midterm_duration' class='editinput'>" + textBox118.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='midterm_total_workload' class='editinput'>" + textBox119.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Final Sınavı" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='final_number' class='editinput'>" + textBox120.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='final_duration' class='editinput'>" + textBox121.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='final_total_workload' class='editinput'>" + textBox122.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "&nbsp;" + "</td>");
                writer.WriteLine("<td>" + "&nbsp;" + "</td>");
                writer.WriteLine("<td>" + "<strong>" + "Toplam" + "</strong>" + "</td>");
                writer.WriteLine("<td align='center' style='font-weight: bold;'>");
                writer.WriteLine("<div class='editinput'>" + textBox123.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>" + "</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("<p>" + "&nbsp;" + "</p>");
                writer.WriteLine("<div>");
                writer.WriteLine("<h3>" + "<strong>" + "DERSİN ÖĞRENME ÇIKTILARININ PROGRAM YETERLİLİKLERİ İLE İLİŞKİSİ" + "</strong>" + "</h3>");
                writer.WriteLine("</div>");
                writer.WriteLine("<div class='table-responsive'>");
                writer.WriteLine("<table align='center' cellpadding='2' cellspacing='2' class='table table-condensed table-bordered' id='yeters'>");
                writer.WriteLine("<tbody>" + "<tr class='table_top'>");
                writer.WriteLine("<td rowspan='2'>");
                writer.WriteLine("<div align='center'>" + "#" + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td rowspan='2'>");
                writer.WriteLine("<strong>" + "Program Yeterlilikleri / Çıktıları" + "</strong>" + "</td>");
                writer.WriteLine("<td colspan='5'>");
                writer.WriteLine("<div align='center'>" + "<strong>" + "* Katkı Düzeyi" + "</strong>" + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td width='30' class='table_top'>");
                writer.WriteLine("<div align='center'>" + "1" + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' class='table_top'>");
                writer.WriteLine("<div align='center'>" + "2" + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' class='table_top'>");
                writer.WriteLine("<div align='center'>" + "3" + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' class='table_top'>");
                writer.WriteLine("<div align='center'>" + "4" + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' class='table_top'>");
                writer.WriteLine("<div align='center'>" + "5" + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id=''>");
                writer.WriteLine("<td>" + "<strong>" + "1" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Matematik, Fen Bilimleri ve Bilgisayar Mühendisliği konularında yeterli bilgi sahibidir; bu alanlardaki kuramsal ve uygulamalı bilgileri, karmaşık mühendislik problemlerinde kullanır." + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox124.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox125.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox126.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox127.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox128.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='2'>");
                writer.WriteLine("<td>" + "<strong>" + "2" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Karmaşık Bilgisayar Mühendisliği problemlerini saptar, tanımlar, formüle eder ve çözer; bu amaca uygun analiz ve modelleme yöntemlerini seçer ve uygular." + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox129.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox130.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox131.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox132.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox133.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='3'>");
                writer.WriteLine("<td>" + "<strong>" + "3" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Karmaşık bir sistemi, süreci, cihazı veya ürünü gerçekçi kısıtlar ve koşullar altında, belirli gereksinimleri karşılayacak şekilde tasarlar; bu amaçla modern tasarım yöntemlerini uygular." + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox134.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox135.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox136.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox137.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox138.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='4'>");
                writer.WriteLine("<td>" + "<strong>" + "4" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Bilgisayar Mühendisliği uygulamalarında karşılaşılan karmaşık problemlerin analizi ve çözümü için gerekli olan modern teknik ve araçları geliştirir, seçer ve kullanır; bilişim teknolojilerini etkin bir şekilde kullanır." + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox139.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox140.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox141.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox142.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox143.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='5'>");
                writer.WriteLine("<td>" + "<strong>" + "5" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Karmaşık Bilgisayar Mühendisliği problemlerinin veya araştırma konularının incelenmesi için deney tasarlar, deney yapar, veri toplar, sonuçları analiz eder ve yorumlar." + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox144.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox145.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox146.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox147.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox148.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='6'>");
                writer.WriteLine("<td>" + "<strong>" + "6" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Bilgisayar Mühendisliği disiplini içinde ve çok disiplinli takımlarda etkin biçimde çalışır; bireysel çalışma sergiler." + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox149.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox150.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox151.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox152.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox153.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='7'>");
                writer.WriteLine("<td>" + "<strong>" + "7" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Türkçe sözlü ve yazılı etkin iletişim kurar; etkin rapor yazar ve yazılı raporları anlar, tasarım ve üretim raporları hazırlar, etkin sunum yapar, açık ve anlaşılır talimat verir ve alır." + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox154.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox155.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox156.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox157.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox158.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='8'>");
                writer.WriteLine("<td>" + "<strong>" + "8" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Bilgisayar Mühendisliği uygulamalarının evrensel ve toplumsal boyutlarda sağlık, çevre ve güvenlik üzerindeki etkileri ve çağın mühendislik alanına yansıyan sorunları hakkında bilgi sahibidir; mühendislik çözümlerinin hukuksal sonuçlarının farkındadır." + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox159.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox160.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox161.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox162.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox163.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='9'>");
                writer.WriteLine("<td>" + "<strong>" + "9" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Etik ilkelerine uygun davranma, mesleki ve etik sorumluluk bilincine sahiptir; mühendislik uygulamalarında kullanılan standartlar hakkında bilgi sahibidir." + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox164.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox165.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox166.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox167.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox168.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='10'>");
                writer.WriteLine("<td>" + "<strong>" + "10" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Proje yönetimi, risk yönetimi ve değişiklik yönetimi gibi, iş hayatındaki uygulamalar hakkında bilgi sahibidir; girişimcilik, yenilikçilik hakkında bilinçlidir; sürdürülebilir kalkınma hakkında bilgi sahibidir." + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox169.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox170.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox171.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox172.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox173.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='11'>");
                writer.WriteLine("<td>" + "<strong>" + "11" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Bir yabancı dili kullanarak Bilgisayar Mühendisliği ile ilişkili konularda, bilgi toplar ve meslektaşları ile iletişim kurar. (European Language Portfolio Global Scale, Level B1)" + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox174.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox175.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox176.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox177.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox178.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='12'>");
                writer.WriteLine("<td>" + "<strong>" + "12" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "İkinci yabancı dili orta düzeyde kullanır" + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox179.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox180.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox181.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox182.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox183.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='13'>");
                writer.WriteLine("<td>" + "<strong>" + "13" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Yaşam boyu öğrenmenin gerekliliği bilincindedir; bilgiye erişir, bilim ve teknolojideki gelişmeleri izler ve kendini sürekli yeniler; insanlık tarihi boyunca oluşan bilgi birikimini Bilgisayar Mühendisliği alanıyla ilişkilendirir." + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox184.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox185.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox186.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox187.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox188.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>" + "</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("<p align='right'>" + "* 1 Lowest, 2 Low, 3 Average, 4 High, 5 Highest" + "</p>");
                writer.WriteLine("<p>" + "&nbsp;" + "</p>" + "<hr>");
                writer.WriteLine("</div>");
                writer.WriteLine("</div>");

            }
        }
    }
}
