using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.IO;

namespace WindowsFormsApplication2
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            using (StreamWriter writer = new StreamWriter(@"C:\" + textBox2.Text+ "_syllabus.html"))
            {
                writer.WriteLine("<link rel='preload' href='https://www.ieu.edu.tr/css/yenicss/1.min.css?ver=1.2' media='screen' as='style'>");
                writer.WriteLine("<link href='https://www.ieu.edu.tr/css/yenicss/1.min.css?ver=1.2' rel='stylesheet'>");
                writer.WriteLine("<div>");
                writer.WriteLine("<div class='card'>");
                writer.WriteLine("<div class='card-body'>");
                writer.WriteLine("<div class='table-responsive'>");
                writer.WriteLine("<table align='center' cellpadding='2' cellspacing='2' class='table table-condensed table-bordered '>");
                writer.WriteLine("<tbody>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td class='sy-label' style='padding:20px;'>");
                writer.WriteLine("<strong>" + "Dersin Adı");
                writer.WriteLine("</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td style='padding:20px;'>");
                writer.WriteLine("<div class='editinput' id='course_name'>" + textBox1.Text);
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>");
                writer.WriteLine("</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("<div class='table-responsive'>");
                writer.WriteLine("<table align='center' cellpadding='2' cellspacing='2' class='table table-condensed table-bordered transpose'>");
                writer.WriteLine("<tbody>");
                writer.WriteLine("<tr class='sy-label'>");
                writer.WriteLine("<td scope='col'>");
                writer.WriteLine("<div align='center'>");
                writer.WriteLine("<strong>" + "Kodu");
                writer.WriteLine("</strong>");
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td scope='col'>");
                writer.WriteLine("<div align='center'>");
                writer.WriteLine("<strong>" + "Yarıyıl");
                writer.WriteLine("</strong>");
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td scope='col'>");
                writer.WriteLine("<div align='center'>");
                writer.WriteLine("<strong>" + "Teori");
                writer.WriteLine("<br>" + "(saat/hafta)");
                writer.WriteLine("</strong>");
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td scope='col'>");
                writer.WriteLine("<div align='center'>");
                writer.WriteLine("<strong>" + "Uygulama/Lab");
                writer.WriteLine("<br>" + "(saat/hafta)");
                writer.WriteLine("</strong>");
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td scope='col'>");
                writer.WriteLine("<div align='center'>");
                writer.WriteLine("<strong>" + "Yerel Kredi");
                writer.WriteLine("</strong>");
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td scope='col'>");
                writer.WriteLine("<div align='center'>");
                writer.WriteLine("<strong>" + "AKTS");
                writer.WriteLine("</strong>");
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div align='center'>" + textBox2.Text);
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='semester' class='editinput' align='center'>" + textBox3.Text);
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div align='center' id='weekly_hours' class='editinput'>" + textBox4.Text);
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div align='center' id='app_hours' class='editinput'>" + textBox5.Text);
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='ieu_credit' class='editinput' align='center'>" + textBox6.Text);
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='ects_credit' class='editinput' align='center'>" + textBox7.Text);
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>");
                writer.WriteLine("</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("<br>");
                writer.WriteLine("<div class='table-responsive'>");
                writer.WriteLine("<table align='center' cellpadding='2' cellspacing='2' class='table table-condensed table-bordered'>");
                writer.WriteLine("<tbody>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td style='width:20%' valign='top' class='sy-label'>");
                writer.WriteLine("<strong>" + "Ön Koşul(lar)");
                writer.WriteLine("</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td colspan='6'>");
                writer.WriteLine("<div id='pre_requisites'>");
                writer.WriteLine("<table width='100%'>");
                writer.WriteLine("<tbody>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td style='border:none;'>" + "&nbsp;" + "</td>");
                writer.WriteLine("<td style='border:none;'>" + textBox8.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>");
                writer.WriteLine("</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td class='sy-label'>");
                writer.WriteLine("<strong>" + "Dersin Dili");
                writer.WriteLine("</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div class='editinput' id='course_lang'>" + textBox9.Text);
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td class='sy-label'>");
                writer.WriteLine("<strong>" + "Dersin Türü");
                writer.WriteLine("</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div class='editinput' id='course_type'>" + textBox10.Text);
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td class='sy-label'>");
                writer.WriteLine("<strong>" + "Dersin Düzeyi");
                writer.WriteLine("</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div class='editselect' id='course_level'>" + textBox11.Text);
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td class='sy-label'>");
                writer.WriteLine("<strong>" + "Dersin Koordinatörü");
                writer.WriteLine("</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<ul id='coordinator_list'>" + "<li>" + textBox12.Text + "</li>" + "</ul>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td valign='top' class='sy-label'>");
                writer.WriteLine("<strong>" + "Öğretim Elemanı");
                writer.WriteLine("</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<ul id='lecturer_list'>");
                writer.WriteLine("<li>" + textBox13.Text + "</li>");
                writer.WriteLine("</ul>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td class='sy-label'>");
                writer.WriteLine("<strong>" + "Yardımcıları");
                writer.WriteLine("</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<ul id='lecturer_list'>");
                writer.WriteLine("<li>" + textBox14.Text + "</li>");
                writer.WriteLine("</ul>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>");
                writer.WriteLine("</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("<div class='table-responsive'>");
                writer.WriteLine("<table align='center' cellpadding='2' cellspacing='2' class='table table-condensed table-bordered'>");
                writer.WriteLine("<tbody>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td style='width:20%' valign='top' class='sy-label'>");
                writer.WriteLine("<strong>" + "Dersin Amacı");
                writer.WriteLine("</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox15.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td valign='top' class='sy-label'>");
                writer.WriteLine("<strong>" + "Öğrenme Çıktıları");
                writer.WriteLine("</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<span>" + "Bu dersi başarıyla tamamlayan öğrenciler;");
                writer.WriteLine("</span>");
                writer.WriteLine("<ul id='outcome'>");
                writer.WriteLine("<li id='li0'>" + textBox16.Text + "</li>");
                writer.WriteLine("</ul>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td valign='top' class='sy-label'>");
                writer.WriteLine("<strong>" + "Ders Tanımı");
                writer.WriteLine("</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox17.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>");
                writer.WriteLine("</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("<p>" + "&nbsp;" + "</p>");
                writer.WriteLine("<div class='table-responsive'>");
                writer.WriteLine("<table align='center' cellpadding='2' cellspacing='2' class='table table-condensed table-bordered'>");
                writer.WriteLine("<tbody>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td rowspan='5' class='sy-label' style='width:20%'");
                writer.WriteLine("<div align='center'>");
                writer.WriteLine("<p><br><br>");
                writer.WriteLine("<strong>" + "Dersin Kategorisi" + "</strong>");
                writer.WriteLine("</p>");
                writer.WriteLine("</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + "Temel Ders" + "</td>");
                writer.WriteLine("<td class='veri'>");
                writer.WriteLine("<div id='core_course' class='editcat' align='center'>" + textBox18.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Uzmanlık/Alan Dersleri" + "</td>");
                writer.WriteLine("<td class='veri' width='50'>");
                writer.WriteLine("<div id='major_area' class='editcat' align='center'>" + textBox19.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Destek Dersleri" + "</td>");
                writer.WriteLine("<td class='veri' width='50'>");
                writer.WriteLine("<div align='center' class='editcat' id='supportive_courses'>" + textBox20.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "İletişim ve Yönetim Becerileri Dersleri" + "</td>");
                writer.WriteLine("<td class='veri' width='50'>");
                writer.WriteLine("<div id='media_man_skills' class='editcat' align='center'>" + textBox21.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Aktarılabilir Beceri Dersleri" + "</td>");
                writer.WriteLine("<td class='veri' width='50'>");
                writer.WriteLine("<div id='trans_skills' class='editcat' align='center'>" + textBox22.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>" + "</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("<p>" + "&nbsp;" + "</p>");
                writer.WriteLine("<div>" + "<h3>");
                writer.WriteLine("<strong>" + "HAFTALIK KONULAR VE İLGİLİ ÖN HAZIRLIK ÇALIŞMALARI" + "</strong>");
                writer.WriteLine("</h3>" + "</div>");
                writer.WriteLine("<div class='table-responsive'>");
                writer.WriteLine("<table align='center' cellpadding='2' cellspacing='2' class='table table-condensed table-bordered' id='weeks'>");
                writer.WriteLine("<tbody>" + "<tr class='table_top'>");
                writer.WriteLine("<td class='text-center' style='width:5%'>");
                writer.WriteLine("<strong>" + "Hafta" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "Konular" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td style:'width:30%'>");
                writer.WriteLine("<strong>" + "Ön Hazırlık" + "</strong>");
                writer.WriteLine("</td>" + "</tr>");
                writer.WriteLine("<tr id='hafta_1'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "1" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox23.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox24.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_2'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "2" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox25.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox26.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_3'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "3" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox27.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox28.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_4'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "4" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox29.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox30.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_5'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "5" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox31.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox32.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_6'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "6" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox33.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox34.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_7'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "7" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox35.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox36.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_8'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "8" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox37.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox38.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_9'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "9" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox39.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox40.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_10'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "10" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox41.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox42.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_11'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "11" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox43.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox44.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_12'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "12" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox45.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox46.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_13'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "13" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox47.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox48.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_14'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "14" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox49.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox50.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_15'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "15" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox51.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox52.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='hafta_16'>");
                writer.WriteLine("<td>");
                writer.WriteLine("<strong>" + "16" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox53.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + textBox54.Text);
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>" + "</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("<br>");
                writer.WriteLine("<div class='table-responsive'>");
                writer.WriteLine("<table align='center' cellpadding='2' cellspacing='2' class='table table-condensed table-bordered'>");
                writer.WriteLine("<tbody>" + "<tr>");
                writer.WriteLine("<td style='width:20%' valign='top'>");
                writer.WriteLine("<strong>" + "Ders Kitabı" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + "<p>" + textBox55.Text + "</p>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td valign='top'>");
                writer.WriteLine("<strong>" + "Önerilen Okumalar/Materyaller" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>" + "<p>" + textBox56.Text + "</p>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>" + "</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("<p>" + "&nbsp;" + "</p>");
                writer.WriteLine("<div>");
                writer.WriteLine("<h3>" + "<strong>" + "DEĞERLENDİRME ÖLÇÜTLERİ" + "</strong>" + "</h3>");
                writer.WriteLine("</div>");
                writer.WriteLine("<div class='table-responsive'>");
                writer.WriteLine("<table align='center' cellpadding='2' cellspacing='2' class='table table-condensed table-bordered' id='evaluation_table1'>");
                writer.WriteLine("<tbody>" + "<tr class='table-top'>");
                writer.WriteLine("<td style:'width:70%'>" + "<strong>" + "Yarıyıl Aktiviteleri" + "</strong>" + "</td>");
                writer.WriteLine("<td style:'width:15%' align='center'>" + "<strong>" + "Sayı" + "</strong>" + "</td>");
                writer.WriteLine("<td style:'width:15%' align='center'>" + "<strong>" + "Katkı Payı %" + "</strong>" + "</td>");
                writer.WriteLine("<td style:'width:15%' align='center'>" + "<strong>" + "LO1" + "</strong>" + "</td>");
                writer.WriteLine("<td style:'width:15%' align='center'>" + "<strong>" + "LO2" + "</strong>" + "</td>");
                writer.WriteLine("<td style:'width:15%' align='center'>" + "<strong>" + "LO3" + "</strong>" + "</td>");
                writer.WriteLine("<td style:'width:15%' align='center'>" + "<strong>" + "LO4" + "</strong>" + "</td>");
                writer.WriteLine("<td style:'width:15%' align='center'>" + "<strong>" + "LO5" + "</strong>" + "</td>");
                writer.WriteLine("<td style:'width:15%' align='center'>" + "<strong>" + "LO6" + "</strong>" + "</td>");
                writer.WriteLine("<td style:'width:15%' align='center'>" + "<strong>" + "LO7" + "</strong>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Katılım" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='attendance_no'>" + textBox57.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='attendance_per'>" + textBox58.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='attendance_lo1'>" + textBox59.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='attendance_lo2'>" + textBox60.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='attendance_lo3'>" + textBox61.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='attendance_lo4'>" + textBox62.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='attendance_lo5'>" + textBox63.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='attendance_lo6'>" + textBox64.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='attendance_lo7'>" + textBox65.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Labaratuvar/Uygulama" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='lab_no'>" + textBox66.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='lab_per'>" + textBox67.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='lab_lo1'>" + textBox68.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='lab_lo2'>" + textBox69.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='lab_lo3'>" + textBox70.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='lab_lo4'>" + textBox71.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='lab_lo5'>" + textBox72.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='lab_lo6'>" + textBox73.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='lab_lo7'>" + textBox74.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Arazi Çalışması" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='fieldwork_no'>" + textBox75.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='fieldwork_per'>" + textBox76.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='fieldwork_lo1'>" + textBox77.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='fieldwork_lo2'>" + textBox78.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='fieldwork_lo3'>" + textBox79.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='fieldwork_lo4'>" + textBox80.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='fieldwork_lo5'>" + textBox81.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='fieldwork_lo6'>" + textBox82.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='fieldwork_lo7'>" + textBox83.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Küçük Sınav/ Stüdyo Kritiği" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='quiz_no'>" + textBox84.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='quiz_per'>" + textBox85.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='quiz_lo1'>" + textBox86.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='quiz_lo2'>" + textBox87.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='quiz_lo3'>" + textBox88.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='quiz_lo4'>" + textBox89.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='quiz_lo5'>" + textBox90.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='quiz_lo6'>" + textBox91.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='quiz_lo7'>" + textBox92.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Ödev" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='homework_no'>" + textBox93.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='homework_per'>" + textBox94.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='homework_lo1'>" + textBox95.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='homework_lo2'>" + textBox96.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='homework_lo3'>" + textBox97.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='homework_lo4'>" + textBox98.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='homework_lo5'>" + textBox99.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='homework_lo6'>" + textBox100.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='homework_lo7'>" + textBox101.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Sunum / Jüri Önünde Sunum" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='presentation_no'>" + textBox102.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='presentation_per'>" + textBox103.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='presentation_lo1'>" + textBox104.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='presentation_lo2'>" + textBox105.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='presentation_lo3'>" + textBox106.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='presentation_lo4'>" + textBox107.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='presentation_lo5'>" + textBox108.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='presentation_lo6'>" + textBox109.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='presentation_lo7'>" + textBox110.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Proje" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='project_no'>" + textBox111.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='project_per'>" + textBox112.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='project_lo1'>" + textBox113.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='project_lo2'>" + textBox114.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='project_lo3'>" + textBox115.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='project_lo4'>" + textBox116.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='project_lo5'>" + textBox117.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='project_lo6'>" + textBox118.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='project_lo7'>" + textBox119.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Seminer / Çalıştay" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='seminar_no'>" + textBox120.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='seminar_per'>" + textBox121.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='seminar_lo1'>" + textBox122.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='seminar_lo2'>" + textBox123.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='seminar_lo3'>" + textBox124.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='seminar_lo4'>" + textBox125.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='seminar_lo5'>" + textBox126.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='seminar_lo6'>" + textBox127.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='seminar_lo7'>" + textBox128.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Sözlü Sınav" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='portfolios__no'>" + textBox129.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='portfolios_per'>" + textBox130.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='portfolios_lo1'>" + textBox131.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='portfolios_lo2'>" + textBox132.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='portfolios_lo3'>" + textBox133.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='portfolios_lo4'>" + textBox134.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='portfolios_lo5'>" + textBox135.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='portfolios_lo6'>" + textBox136.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='portfolios_lo7'>" + textBox137.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Ara Sınav" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='midterm_no'>" + textBox138.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='midterm_per'>" + textBox139.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='midterm_lo1'>" + textBox140.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='midterm_lo2'>" + textBox141.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='midterm_lo3'>" + textBox142.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='midterm_lo4'>" + textBox143.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='midterm_lo5'>" + textBox144.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='midterm_lo6'>" + textBox145.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='midterm_lo7'>" + textBox146.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Final Sınavı" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='final_no'>" + textBox147.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='final_per'>" + textBox148.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='final_lo1'>" + textBox149.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='final_lo2'>" + textBox150.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='final_lo3'>" + textBox151.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='final_lo4'>" + textBox152.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='final_lo5'>" + textBox153.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='final_lo6'>" + textBox154.Text + "</div>" + "</td>");
                writer.WriteLine("<td>" + "<div class='editinput' id='final_lo7'>" + textBox155.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td align='right'>");
                writer.WriteLine("<strong>" + "Toplam" + "</strong>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div class='editinput' id='ara_total_no'>" + textBox156.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div class='editinput' id='ara_total_per'>" + textBox157.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div class='editinput' id='ara_total_lo1'>" + textBox158.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div class='editinput' id='ara_total_lo2'>" + textBox159.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div class='editinput' id='ara_total_lo3'>" + textBox160.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div class='editinput' id='ara_total_lo4'>" + textBox161.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div class='editinput' id='ara_total_lo5'>" + textBox162.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div class='editinput' id='ara_total_lo6'>" + textBox163.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div class='editinput' id='ara_total_lo7'>" + textBox164.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>" + "</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("<br>");
                writer.WriteLine("<div class='table-responsive'>");
                writer.WriteLine("<table align='center' cellpadding='2' cellspacing='2' class='table table-condensed table-bordered' id='evaluation_table2'>");
                writer.WriteLine("<tbody>" + "<tr style='background-color:#ff6600; color:#fff; font-weight:100;'>");
                writer.WriteLine("<td style='width:70%'>" + "Yarıyıl Çalışmalarının Başarı Notuna Katkısı" + "</td>");
                writer.WriteLine("<td style='width:15%' align='center' width='150'>" + "<div>" + textBox165.Text + "</div>" + "</td>");
                writer.WriteLine("<td style='width:15%' align='center' width='150'>" + "<div>" + textBox166.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr style='background-color:#df520f; color:#fff; font-weight:400;'>");
                writer.WriteLine("<td>" + "Yarıyıl sonu Çalışmalarının Başarı Notuna Katkısı" + "</td>");
                writer.WriteLine("<td align='center' width='150'>" + "<div>" + textBox167.Text + "</div>" + "</td>");
                writer.WriteLine("<td align='center' width='150'>" + "<div>" + textBox168.Text + "</div>" + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td align='right'>" + "<strong>" + "Toplam" + "</strong>" + "</td>");
                writer.WriteLine("<td align='center' id='total_no' style='font-weight: bold;'>" + textBox169.Text + "</td>");
                writer.WriteLine("<td align='center' id='total_no' style='font-weight: bold;'>" + textBox170.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>" + "</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("<div>");
                writer.WriteLine("<h3>" + "<strong>" + "AKTS/ İŞ YÜKÜ TABLOSU" + "</strong>" + "</h3>");
                writer.WriteLine("</div>");
                writer.WriteLine("<div class='table-responsive'>");
                writer.WriteLine("<table align='center' cellpadding='2' cellspacing='2' class='table table-condensed table-bordered' id='workload_table'>");
                writer.WriteLine("<thead>");
                writer.WriteLine("<tr class='table_top'>");
                writer.WriteLine("<th style='width:55%'>" + "<strong>" + "Yarıyıl Aktiviteleri" + "</strong>" + "</th>");
                writer.WriteLine("<th style='width:15%' class='text-center'>" + "<strong>" + "Sayı" + "</strong>" + "</th>");
                writer.WriteLine("<th style='width:15%' class='text-center'>" + "<strong>" + "Süre (Saat)" + "</strong>" + "</th>");
                writer.WriteLine("<th style='width:15%' class='text-center'>" + "<strong>" + "İş Yükü" + "</strong>" + "</th>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</thead>");
                writer.WriteLine("<tbody>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Teorik Ders Saati" + "<br>" + "<small>" + "<i>" + "(Sınav Haftası Dahildir: 16 x Teorik Ders Saati)" + "</i>" + "</small>" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='course_hour_number' class='editinput'>" + textBox171.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='course_hour_duration' class='editinput'>" + textBox172.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='course_hour_total_workload' class='editinput'>" + textBox173.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Labaratuvar/Uygulama Ders Saati" + "<br>" + "<small>" + "<i>" + "(Sınav Haftası Dahildir: 16 x Labaratuvar/Uygulama Ders Saati)" + "</i>" + "</small>" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='lab_number' class='editinput'>" + textBox174.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='lab_duration' class='editinput'>" + textBox175.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='lab_total_workload' class='editinput'>" + textBox176.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Sınıf Dışı Ders Çalışması" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='out_hour_number' class='editinput'>" + textBox177.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='out_hour_duration' class='editinput'>" + textBox178.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='out_hour_duration_total_workload' class='editinput'>" + textBox179.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Arazi Çalışması" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='fieldwork_number' class='editinput'>" + textBox180.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='fieldwork_duration' class='editinput'>" + textBox181.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='fielwork_total_number' class='editinput'>" + textBox182.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Küçük Sınav / Stüdyo Kritiği" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='quizess_number' class='editinput'>" + textBox183.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='quizess_duration' class='editinput'>" + textBox184.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='quizess_total_workload' class='editinput'>" + textBox185.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Ödev" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='homework_number' class='editinput'>" + textBox186.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='homework_duration' class='editinput'>" + textBox187.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='homework_total_workload' class='editinput'>" + textBox188.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Sunum / Jüri Önünde Sunum" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='presentation_number' class='editinput'>" + textBox189.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='presentation_duration' class='editinput'>" + textBox190.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='presentation_total_workload' class='editinput'>" + textBox191.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Proje" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='project_number' class='editinput'>" + textBox192.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='project_duration' class='editinput'>" + textBox193.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='project_total_workload' class='editinput'>" + textBox194.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Seminer / Çalıştay" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='seminar_number' class='editinput'>" + textBox195.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='seminar_duration' class='editinput'>" + textBox196.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='seminar_total_workload' class='editinput'>" + textBox197.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Sözlü Sınav" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='portfolios_number' class='editinput'>" + textBox198.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='portfolios_duration' class='editinput'>" + textBox199.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='portfolios_total_workload' class='editinput'>" + textBox200.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Ara Sınavlar" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='midterm_number' class='editinput'>" + textBox201.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='midterm_duration' class='editinput'>" + textBox202.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='midterm_total_workload' class='editinput'>" + textBox203.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "Final Sınavı" + "</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='final_number' class='editinput'>" + textBox204.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='final_duration' class='editinput'>" + textBox205.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td>");
                writer.WriteLine("<div id='final_total_workload' class='editinput'>" + textBox206.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td>" + "&nbsp;" + "</td>");
                writer.WriteLine("<td>" + "&nbsp;" + "</td>");
                writer.WriteLine("<td>" + "<strong>" + "Toplam" + "</strong>" + "</td>");
                writer.WriteLine("<td align='center' style='font-weight: bold;'>");
                writer.WriteLine("<div class='editinput'>" + textBox207.Text + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>" + "</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("<p>" + "&nbsp;" + "</p>");
                writer.WriteLine("<div>");
                writer.WriteLine("<h3>" + "<strong>" + "DERSİN ÖĞRENME ÇIKTILARININ PROGRAM YETERLİLİKLERİ İLE İLİŞKİSİ" + "</strong>" + "</h3>");
                writer.WriteLine("</div>");
                writer.WriteLine("<div class='table-responsive'>");
                writer.WriteLine("<table align='center' cellpadding='2' cellspacing='2' class='table table-condensed table-bordered' id='yeters'>");
                writer.WriteLine("<tbody>" + "<tr class='table_top'>");
                writer.WriteLine("<td rowspan='2'>");
                writer.WriteLine("<div align='center'>" + "#" + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td rowspan='2'>");
                writer.WriteLine("<strong>" + "Program Yeterlilikleri / Çıktıları" + "</strong>" + "</td>");
                writer.WriteLine("<td colspan='5'>");
                writer.WriteLine("<div align='center'>" + "<strong>" + "* Katkı Düzeyi" + "</strong>" + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr>");
                writer.WriteLine("<td width='30' class='table_top'>");
                writer.WriteLine("<div align='center'>" + "1" + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' class='table_top'>");
                writer.WriteLine("<div align='center'>" + "2" + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' class='table_top'>");
                writer.WriteLine("<div align='center'>" + "3" + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' class='table_top'>");
                writer.WriteLine("<div align='center'>" + "4" + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' class='table_top'>");
                writer.WriteLine("<div align='center'>" + "5" + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' class='table_top'>");
                writer.WriteLine("<div align='center'>" + "LO#" + "</div>");
                writer.WriteLine("</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id=''>");
                writer.WriteLine("<td>" + "<strong>" + "1" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Matematik, Fen Bilimleri ve Bilgisayar Mühendisliği konularında yeterli bilgi sahibidir; bu alanlardaki kuramsal ve uygulamalı bilgileri, karmaşık mühendislik problemlerinde kullanır." + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox208.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox209.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox210.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox211.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox212.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox213.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='2'>");
                writer.WriteLine("<td>" + "<strong>" + "2" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Karmaşık Bilgisayar Mühendisliği problemlerini saptar, tanımlar, formüle eder ve çözer; bu amaca uygun analiz ve modelleme yöntemlerini seçer ve uygular." + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox214.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox215.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox216.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox217.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox218.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox219.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='3'>");
                writer.WriteLine("<td>" + "<strong>" + "3" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Karmaşık bir sistemi, süreci, cihazı veya ürünü gerçekçi kısıtlar ve koşullar altında, belirli gereksinimleri karşılayacak şekilde tasarlar; bu amaçla modern tasarım yöntemlerini uygular." + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox220.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox221.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox222.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox223.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox224.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox225.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='4'>");
                writer.WriteLine("<td>" + "<strong>" + "4" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Bilgisayar Mühendisliği uygulamalarında karşılaşılan karmaşık problemlerin analizi ve çözümü için gerekli olan modern teknik ve araçları geliştirir, seçer ve kullanır; bilişim teknolojilerini etkin bir şekilde kullanır." + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox226.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox227.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox228.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox229.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox230.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox231.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='5'>");
                writer.WriteLine("<td>" + "<strong>" + "5" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Karmaşık Bilgisayar Mühendisliği problemlerinin veya araştırma konularının incelenmesi için deney tasarlar, deney yapar, veri toplar, sonuçları analiz eder ve yorumlar." + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox232.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox233.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox234.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox235.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox236.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox237.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='6'>");
                writer.WriteLine("<td>" + "<strong>" + "6" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Bilgisayar Mühendisliği disiplini içinde ve çok disiplinli takımlarda etkin biçimde çalışır; bireysel çalışma sergiler." + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox238.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox239.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox240.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox241.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox242.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox243.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='7'>");
                writer.WriteLine("<td>" + "<strong>" + "7" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Türkçe sözlü ve yazılı etkin iletişim kurar; etkin rapor yazar ve yazılı raporları anlar, tasarım ve üretim raporları hazırlar, etkin sunum yapar, açık ve anlaşılır talimat verir ve alır." + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox244.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox245.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox246.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox247.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox248.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox249.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='8'>");
                writer.WriteLine("<td>" + "<strong>" + "8" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Bilgisayar Mühendisliği uygulamalarının evrensel ve toplumsal boyutlarda sağlık, çevre ve güvenlik üzerindeki etkileri ve çağın mühendislik alanına yansıyan sorunları hakkında bilgi sahibidir; mühendislik çözümlerinin hukuksal sonuçlarının farkındadır." + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox250.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox251.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox252.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox253.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox254.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox255.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='9'>");
                writer.WriteLine("<td>" + "<strong>" + "9" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Etik ilkelerine uygun davranma, mesleki ve etik sorumluluk bilincine sahiptir; mühendislik uygulamalarında kullanılan standartlar hakkında bilgi sahibidir." + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox256.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox257.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox258.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox259.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox260.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox261.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='10'>");
                writer.WriteLine("<td>" + "<strong>" + "10" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Proje yönetimi, risk yönetimi ve değişiklik yönetimi gibi, iş hayatındaki uygulamalar hakkında bilgi sahibidir; girişimcilik, yenilikçilik hakkında bilinçlidir; sürdürülebilir kalkınma hakkında bilgi sahibidir." + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox262.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox263.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox264.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox265.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox266.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox267.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='11'>");
                writer.WriteLine("<td>" + "<strong>" + "11" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Bir yabancı dili kullanarak Bilgisayar Mühendisliği ile ilişkili konularda, bilgi toplar ve meslektaşları ile iletişim kurar. (European Language Portfolio Global Scale, Level B1)" + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox268.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox269.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox270.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox271.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox272.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox273.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='12'>");
                writer.WriteLine("<td>" + "<strong>" + "12" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "İkinci yabancı dili orta düzeyde kullanır" + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox274.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox275.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox276.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox277.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox278.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox279.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("<tr id='13'>");
                writer.WriteLine("<td>" + "<strong>" + "13" + "</strong>" + "</td>");
                writer.WriteLine("<td class='outcomeAlert'>");
                writer.WriteLine("<p>" + "Yaşam boyu öğrenmenin gerekliliği bilincindedir; bilgiye erişir, bilim ve teknolojideki gelişmeleri izler ve kendini sürekli yeniler; insanlık tarihi boyunca oluşan bilgi birikimini Bilgisayar Mühendisliği alanıyla ilişkilendirir." + "</p>");
                writer.WriteLine("</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox280.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox281.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox282.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox283.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox284.Text + "</td>");
                writer.WriteLine("<td width='30' style='text-align:center; vertical-align:middle;'> " + textBox285.Text + "</td>");
                writer.WriteLine("</tr>");
                writer.WriteLine("</tbody>" + "</table>");
                writer.WriteLine("</div>");
                writer.WriteLine("<p align='right'>" + "* 1 Lowest, 2 Low, 3 Average, 4 High, 5 Highest" + "</p>");
                writer.WriteLine("<p>" + "&nbsp;" + "</p>" + "<hr>");
                writer.WriteLine("</div>");
                writer.WriteLine("</div>");

            }
        }
    }
}
